### ISSUE TITLE
Custom attribute DSL does not work for inline relation

### ISSUE THREAD

**Issue by kapso** [okuramasafumi/alba#354] opened 2023-12-23 02:16 UTC
Custom attribute DSL does not work for inline relation

```ruby
module AlbaExtension
  # Here attrs are an Array of Symbol
  def time_attributes(*attrs)
    attrs.each do |attr|
      attribute(attr) do |object|
        time = object.__send__(attr)
        time.strftime('%m/%d/%Y')
      end
    end
  end
end

class MemberResource
  include Alba::Resource
  extend AlbaExtension

  attributes :id, :email
  time_attributes :created_at # This works

  one :user do
    extend AlbaExtension # if I comment this, `time_attributes` does not work
    time_attributes :created_at
    attributes :id, :name
  end
end
```

**Comment by okuramasafumi** [comment] 2023-12-23 13:35
I could not reproduce this. Could you create a test case that ensures this issue?

**Comment by okuramasafumi** [comment] 2023-12-23 15:46
@kapso Aha I misunderstood the issue. You can use `helper` instead of `extend`.

**Comment by okuramasafumi** [comment] 2023-12-23 15:57
https://github.com/okuramasafumi/alba/commit/103a89ff7adfdcb8da035e217627336efe8936ad
I added a commit to explain this behavior in README. I'm closing this issue but feel free to reopen it if you have some trouble.

**Closed by okuramasafumi** 2023-12-23 15:57 UTC
Labels: bug

**Comment by kapso** [comment] 2024-04-11 17:46
@okuramasafumi how can I access the `object` inside `time_attributes` method

I am trying to do something like the following...

```ruby
time_attributes : created_at, if: ->(record) { record.has_permission? || params[:has_permission] }
```

so I need to pass the `object` to `if` proc inside `time_attributes` method. What I am trying to do, is it possible? 

Thanks.

**Comment by okuramasafumi** [comment] 2024-04-11 17:50
@kapso You can simply call `object` method anywhere since it's defined in `Alba::Resource`.

**Comment by kapso** [comment] 2024-04-11 20:23
@okuramasafumi I am getting this error when I use `object` inside AlbaExtension method.

```
NameError - undefined local variable or method `object' for class MemberResource:
```

**Comment by okuramasafumi** [comment] 2024-04-12 03:28
@kapso You need to call `object` inside `attribute` call or whatever DSL methods.
Technically, `object` is an *instance* method of `Alba::Resource` and is evaluated with an instance context when used in `attribute` for example.

**Comment by kapso** [comment] 2024-04-12 03:42
@okuramasafumi so I cannot do something like this?

```ruby
def time_attributes(*attrs)
  options = attrs.last.is_a?(Hash) ? attrs.pop : {}
  return if options[:if] && !options[:if].call(object)

  attrs.each do |attr|
    attribute(attr) do |object|
      object.__send__(attr).iso8601
    end
  end
end
```

**Comment by okuramasafumi** [comment] 2024-04-12 04:00
@kapso So this looks an extension of `attribute` method itself. It's not supported directly. Why do you want to implement `if` option yourself?

**Comment by kapso** [comment] 2024-04-12 21:44
@okuramasafumi I figured it out, and solved it passing options to `attribute` method

```ruby
def time_attributes(*attrs)
  options = attrs.last.is_a?(Hash) ? attrs.pop : {}

  attrs.each do |attr|
    attribute(attr, **options) do |object|
      object.__send__(attr).iso8601
    end
  end
end
```

thanks.

**Comment by okuramasafumi** [comment] 2024-04-13 06:06
Sorry now I understand what you want. You're correct but I see it's a little inconvenient. I'll think about the improvements possible.

**Comment by okuramasafumi** [comment] 2024-04-13 06:06
@kapso And for your needs, you could define custom types.
