### ISSUE TITLE
I'm unsure if root_key is not working as intended or I'm misusing it

### ISSUE THREAD

**Issue by Sheikh-TDH** [okuramasafumi/alba#315] opened 2023-05-20 03:10 UTC
## Describe the bug
I have multiple serializers that are using https://github.com/Netflix/fast_jsonapi that I want to migrate to Alba. However I cant get root_key to work. Either that or I'm misusing it

## To Reproduce
When using the fast json serializer the response format looks like:
``
{"data"=>
  {"id"=>"2319",
   "type"=>"provider",
   "attributes"=>
    {"first_name"=>"David",
     "provider_type"=>"Pediatric Allergist",
     "middle_name"=>"P.",
     "last_name"=>"Roger",
     "user_id"=>nil,
     "organization_id"=>7644,
     "full_name_with_creds"=>"David Roger",
     "supervisor_id"=>nil,
     "billable"=>true
      }``
      
 with Alba you get a much nicer output:
 
``{"first_name"=>"David",
 "provider_type"=>"Pediatric Allergist",
 "middle_name"=>"P.",
 "last_name"=>"Roger",
 "user_id"=>nil,
 "organization_id"=>7654,
 "full_name_with_creds"=>"David Roger",
 "supervisor_id"=>nil,
 "billable"=>true
 }``
 
  I then do something like the following to convert the serializer:
  
```
 class ProviderSerializer
  include Alba::Resource
  root_key :data, :attributes

  attributes  :first_name, :provider_type, :middle_name,
              :last_name, :user_id,
              :organization_id, :full_name_with_creds,
              :supervisor_id, :billable
  end
```
  
 

## Expected behavior
The data and attributes are inside a data.attributes hash

## Actual behavior
  the output is exactly as before

## Environment
- Ruby version: 3.1

My question is if this functionality doesnt exist can it be added or if i'm doing it incorrectly, would love some assistance

**Comment by okuramasafumi** [comment] 2023-05-20 08:54
@Sheikh-TDH `root_key` takes two argument, one is for singular resource and another is for multiple resources. https://rubydoc.info/github/okuramasafumi/alba/Alba/Resource#root_key-class_method

If you want to simulate JSON:API spec, one way is to use layout feature.
https://github.com/okuramasafumi/alba#layout

**Comment by okuramasafumi** [comment] 2023-05-20 13:45
It's related to #104 in terms of JSON:API. I've been positive to implement this but it's hard to do so since I don't know much about JSON:API.

**Comment by Sheikh-TDH** [comment] 2023-05-20 14:10
Doing a simple
``  layout inline: proc{
    %({
      "header": "my header",
      "body": #{serialized_json}
    })    
  }``
  
  Still gives out the same format as above and I dont see header or body anywhere

**Comment by okuramasafumi** [comment] 2023-05-20 14:13
Could you provide your whole resource and the output if possible?

**Comment by Sheikh-TDH** [comment] 2023-05-20 14:19
Sure here is the resource:

```
 class ProviderSerializer
  include Alba::Resource
  layout inline: proc{
    %({
      "header": "my header",
      "body": #{serialized_json}
    })    
  }

  attributes  :first_name, :provider_type, :middle_name,
              :last_name, :user_id,
              :organization_id, :full_name_with_creds,
              :supervisor_id, :billable
  end
```

and this is the output


```
  {"first_name"=>"Davendra",
   "provider_type"=>"Pediatric Allergist",
   "middle_name"=>"P.",
   "last_name"=>"Ramkumar",
   "user_id"=>nil,
   "organization_id"=>7688,
   "full_name_with_creds"=>"Davendra Ramkumar",
   "supervisor_id"=>nil,
   "billable"=>true
   }
```

**Comment by okuramasafumi** [comment] 2023-05-21 05:17
@Sheikh-TDH I confirmed that it works with the resource class you gave. Did you reload your environment (e.g. irb)?

**Comment by okuramasafumi** [comment] 2023-05-22 13:34
That's weird. I believe there's something wrong in your environment.

**Comment by okuramasafumi** [comment] 2023-06-10 16:16
@Sheikh-TDH Is the problem still relevant? If not, I'm closing this issue.

**Closed** 2023-07-22 14:58 UTC
Labels: bug
