### ISSUE TITLE
You passed "location" options but ignored.

### ISSUE THREAD

**Issue by mehanoid** [okuramasafumi/alba#347] opened 2023-11-22 11:17 UTC
## Describe the bug
When using the `location` option in the `render` method, a warning is shown

## To Reproduce
```ruby
render json: FooResource.new(foo_instance), location: foo_instance
```

## Expected behavior
No warnings

## Actual behavior
The following message is shown:
```
You passed "location" options but ignored. Please refer to the document: https://github.com/okuramasafumi/alba/blob/main/docs/rails.md
```

## Environment
- Ruby version: 3.2.2
- alba version: 3.0.1

## Additional context
`location` is a valid option for the `render` method.
In the [code](https://github.com/okuramasafumi/alba/blob/b0372c77aa5d6043bba1ee4213b098b3141a6db3/lib/alba/resource.rb#L99) there is a whitelist of options for which alba does not show warnings. Among them there is no `location` option. I think that at least the `location` option should be added to the whitelist too.

Although perhaps it would be better to blacklist the options for which the warning will be shown? As I understand it, the warning was originally added to avoid confusion with the `only` or `except` options, which can be mistakenly added, expecting that only the specified attributes will be shown in the server response.

At the same time, it is arguable whether any warnings are necessary at all. Rails itself does not do any checks for invalid options. Should alba take over this responsibility?

**Comment by okuramasafumi** [comment] 2023-11-23 17:44
@mehanoid Thank you for pointing out. Yes, `location` is a valid option for `render` so this should be fixed.
The problem is how to fix it. As you mentioned `only` and `except` are confusing but others are not, so we can warn only about those two options.
I believe this warning itself is valuable since some people will expect `only` and `except` work and they submit bug reports because they don't work.

**Comment by mehanoid** [comment] 2023-11-24 10:21
I think warning about these two options would be much better than the current implementation anyway. It would also be more resilient to possible future changes in the rails api.

**Comment by okuramasafumi** [comment] 2023-11-30 16:26
@mehanoid I noticed that `methods` option could be also confusing. What do you think about it?

**Comment by mehanoid** [comment] 2023-12-01 09:41
It seems to me that we should be guided by the potential usecases and the result someone might expect when using these options. The `only` and `except` options would obviously be expected to render only the specified attributes. But what would be expected when passing the `methods` option? That the specified methods would be called on the Resource instance? That seems a bit odd.

**Comment by okuramasafumi** [comment] 2023-12-01 17:09
Makes sense. I'll start with `only` and `except` only, and when people think we should add `methods` to that list, I'll do so.

**Closed** 2023-12-02 15:27 UTC
Labels: bug
